import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import "react-toastify/dist/ReactToastify.css";
import { AppProvider } from "@/lib/AppContext";

const font = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aspirely",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <AppProvider>
        <html lang="en">
          <body className={`${font.variable} antialiased  bg-[#202020] mt-20`}>
            {children}
          </body>
        </html>
      </AppProvider>
    </SessionProvider>
  );
}
